# Generated by Django 2.1.4 on 2018-12-24 06:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 12, 24, 6, 16, 54, 36593, tzinfo=utc))),
                ('changed', models.DateTimeField(default=datetime.datetime(2018, 12, 24, 6, 16, 54, 36699, tzinfo=utc))),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
