# Generated by Django 2.1.4 on 2018-12-24 06:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0010_auto_20181224_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 12, 24, 6, 17, 34, 211946, tzinfo=utc))),
                ('changed', models.DateTimeField(default=datetime.datetime(2018, 12, 24, 6, 17, 34, 212043, tzinfo=utc))),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subcategory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='changed',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 6, 17, 34, 210244, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 6, 17, 34, 210155, tzinfo=utc)),
        ),
    ]
