# Generated by Django 2.1.4 on 2018-12-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181224_2343'),
        ('account', '0003_auto_20181224_2038'),
    ]

    operations = [
    ]
