# Generated by Django 2.1.5 on 2019-01-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subcategory_category'),
        ('post', '0002_auto_20190124_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='post',
            name='subcategories',
            field=models.ManyToManyField(related_name='post_subcategories', to='category.Subcategory'),
        ),
    ]
