# Generated by Django 2.1.5 on 2019-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190124_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(to='hashtag.Hashtag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategories',
            field=models.ManyToManyField(to='category.Subcategory'),
        ),
    ]
